# Generated by Django 3.0.3 on 2020-04-09 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0013_auto_20200410_0007'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
