# Generated by Django 3.0.3 on 2020-04-09 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0014_delete_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_purchase', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.Agent')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.Client')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.Property')),
            ],
        ),
    ]
